version: '3.7'

services:
  releases-info:
    build: ./
    image: releases-info
    ports:
      - 80:80
    command: "python main.py"
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml